name: Publish Container image

on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Container Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: extract-tag
        id: tag
        shell: bash
        run: |
          LABEL=$(grep FROM Dockerfile | awk '{print $2}' |tr ':' ' ' |awk '{print $2}')
          echo "LABEL is $LABEL"
          echo "LABEL=$LABEL" >> $GITHUB_OUTPUT
      - name: Build and push Container image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/ueckoken/elasticsearch-jp:${{ steps.tag.env.LABEL }}
